### ISSUE TITLE
Error when converting snippet with passed variable by reference.

### ISSUE THREAD

**Issue by djeux** [m50/psalm-json-to-junit#3]
If the json psalm response contains a snippet with a reference variable:
For example
```
public function send(\Swift_Mime_SimpleMessage $message, &$failedRecipients = null)
```

On report generation it throws an error
```
unterminated entity reference $failedRecipients = null)
```

Htmlencoding the snippet fixes it

**Comment by m50** [comment]
Thanks for that, I'll get a fix out soon!
